name: coba_live
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  states_rebuilder: ^6.4.0
  navigation_builder: ^0.0.4
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  uuid: ^4.4.0
  english_words: ^4.0.0
  validators: ^3.0.0
  keyboard_dismisser: ^3.0.0
  url_strategy: ^0.2.0
  image_picker: ^1.1.2
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
