// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtIq4rTHR8symtDQpI9M46LYbNkjGnqtM',
    appId: '1:319613593405:web:cecd62d03f2407c52f0754',
    messagingSenderId: '319613593405',
    projectId: 'coba-live',
    authDomain: 'coba-live.firebaseapp.com',
    storageBucket: 'coba-live.appspot.com',
    measurementId: 'G-3M7V4Q9088',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByaBOS0hNIWA6VL7MJWHGkDVG7HIhyV1c',
    appId: '1:319613593405:android:bba9a4df6996301d2f0754',
    messagingSenderId: '319613593405',
    projectId: 'coba-live',
    storageBucket: 'coba-live.appspot.com',
  );
}
